name: minnesota_whist
version: 1.0.4+4
description: Flutter implementation of Minnesota Whist with full gameplay.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  fake_async: ^1.3.1
  image: ^4.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/minnesota_whist_icon.png"
  adaptive_icon_background: "#2E7D32"
  adaptive_icon_foreground: "assets/minnesota_whist_icon_foreground.png"
